name: Keep n8n Alive 24/7

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping-space:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Hugging Face
        run: |
          curl -s -L -I "https://hf.space" | head -n 1
          echo "n8n space health check successfully completed."
